### ISSUE TITLE
How to add ssl certificate to react native project ios?

### ISSUE THREAD

**Issue by diego-sh91** [localz/react-native-pinch#1]
Good Afternoon,
Maybe, you could help with this issue..!!! I am new in this topic.

**Comment by paulwcy** [comment]
Hi, you can just copy the certificates into your iOS project. Just don't forget to add them in your Build Phases  > Copy Bundle Resources, in Xcode.

**Comment by jxom** [comment]
I'll add iOS setup instructions to the readme

**Comment by jxom** [comment]
https://github.com/localz/react-native-pinch/commit/80f61b19a25d3386e42afabb8af68c1774409e3f
