### ISSUE TITLE
Can't use different certificates within a single App

### ISSUE THREAD

**Issue by OlDirtyLam** [localz/react-native-pinch#2]
On android, after making any request that specifies a certificate to use, subsequent requests will always use that first certificate when any certificate is specified.

Looks like KeyPinStoreUtil.getInstance just needs to make use of the filename to store and pick which instance to actually return.

**Comment by aprct** [comment]
+1

Please fix this. Returning a new KeyPinStoreUtil does not work, unfortunately.

**Comment by jxom** [comment]
Sorry about the late reply. Will fix this and release within the next few days.

**Comment by jxom** [comment]
Fixed in https://github.com/localz/react-native-pinch/releases/tag/v0.0.15
