### ISSUE TITLE
Fetch is not truly asynchronous on Android

### ISSUE THREAD

**Issue by Fweeper** [localz/react-native-pinch#3]
The `FetchTask` object is executed serially on the same thread as other background tasks, so it will block any subsequent tasks (for example, a call to `AsyncStorage.getItem`, or another `fetch`) until its completion.  Since a particular `fetch` could take a long time depending on the size of the request, network conditions, server availability, etc, I think it's best to move it into the thread pool.  This is easily accomplished by modifying `fetch` in `RNPinch.java`:

```java
@ReactMethod
public void fetch(String endpoint, ReadableMap opts, Callback callback) {
    new FetchTask(opts, callback).executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR, endpoint);
}
```

Looking over the code in `FetchTask.doInBackground`, it does not appear that any of the common pitfalls of parallel threading would apply (e.g. an object's state being modified in one thread in such a way that it would break another thread), so I think that this change is safe.

**Comment by paulwcy** [comment]
Updated in version 0.19
