### ISSUE TITLE
Fail to load certificate

### ISSUE THREAD

**Issue by pedro-f-pereira** [localz/react-native-pinch#39]
Hi,

I am trying to use pinch but when i tried to use sslPinning i get the error:

`java.security.cert.CertificateException: com.android.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: java.io.IOException: BufferedInputStream is closed`

**Comment by hanifmhd** [comment]
please open this issue, i still get it in react native version 0.61.2

**Comment by sudokid91** [comment]
me too!

**Comment by ChameeraFortuna** [comment]
I got the same issue
